services:
  backend-cpu:
    image: felipph/tab-transcribre-pro-backend-gpu:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.cpu
    ports:
      - "8765:8765"
    volumes:
      - ./backend/output:/app/output
    environment:
      - HOST=0.0.0.0
      - PORT=8765
      - MODEL=medium
      - LANGUAGE=pt
    restart: unless-stopped
    profiles:
      - cpu

  backend-gpu:
    image: felipph/tab-transcribre-pro-backend-cpu:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu
    ports:
      - "8766:8765"
    volumes:
      - ./backend/output:/app/output
    environment:
      - HOST=0.0.0.0
      - PORT=8765
      - MODEL=medium
      - LANGUAGE=pt
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    profiles:
      - gpu